version: "3.9"

services:
    app:
        image: nginx:alpine
        container_name: server
        depends_on:
            - router
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            app_net:
                ipv4_address: 172.16.238.08
        ports:
            - 80:80
    router:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: router
        volumes:
            - ./:/router/
        environment:
            - FLASK_APP=/router/router.py
        command: flask run --host=0.0.0.0
        networks:
            app_net:
                aliases:
                    - router-node
        ports:
            - 8181:8181

networks:
    app_net:
      ipam:
        driver: default
        config:
          - subnet: 172.16.238.0/24